### ISSUE TITLE
Cannot pip install fold_to_ascii for py2.7 

### ISSUE THREAD

**Issue by sebrahimi1988** [spanishdict/fold_to_ascii#2]
Is the package written only for Python3? I'm trying to pip install it on my Mac and I am using Python 2.7 but I get this error:

```
Could not find a version that satisfies the requirement fold-to-ascii (from versions: )
No matching distribution found for fold-to-ascii
```

**Comment by sandinmyjoints** [comment]
Thanks for reporting. This should work fine with Python 2.7 -- in fact, that's what we're running it with in our projects!

Until we fix the underlying problem, please try this to get it installed: `pip install 'git+git://github.com/spanishdict/fold_to_ascii.git@v1.0.1'`.

**Comment by sandinmyjoints** [comment]
@sebrahimi1988 This should be fixed now:

```
$ pip install fold-to-ascii
Collecting fold-to-ascii
  Downloading https://files.pythonhosted.org/packages/e7/ec/e5ffcffa3d71e51205a27232df1ed9e74e558520eaf6d181d72dc685a829/fold_to_ascii-1.0.1-py2-none-any.whl
Installing collected packages: fold-to-ascii
Successfully installed fold-to-ascii-1.0.1
```

I'm going to close the issue, but definitely let me know if you try it and it doesn't work.
